[package]
name = "node-libxml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libxml = "0.3.3"
xml_oxide = "0.3.0"
xmltree = "0.10.3"
